### ISSUE TITLE
[Bug] fetch_kospi_symbols

### ISSUE THREAD

**Issue by brayden-jo** [sharebook-kr/mojito#5]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 23: invalid start byte

​

이런 에러가... -_-;;;;;;

아직 쪼랩이라 잘 찾지도 못하는데... 어째건 뒤져서 찾아낸건... 

종목 정보 csv 템프 파일 읽을때 utf-8로 읽는 것이 아닌가... 하는 추측입니다.

​

아침에 사무실에서 돌려보니 또 맥에선 잘 되는군요........

저만 이런걸까요?

**Comment by ohkashi** [comment]
wf1 = open(tmp_fil1, mode="w")
        wf2 = open(tmp_fil2, mode="w")
tmp_file char-set encoding이 명시되지 않아 OS에 따라 다르게 저장하는 게 아닌지?

**Comment by brayden-jo** [comment]
@ohkashi 감사합니다. 시간될 때 확인해보겠습니다.

**Comment by brayden-jo** [comment]
```
Traceback (most recent call last):
  File "c:\Users\brayden\Documents\GitHub\mojito\examples\koreainvestment\fetch_symbols_kospi.py", line 18, in <module>
    symbols = broker.fetch_kospi_symbols()
  File "C:\Users\brayden\Documents\GitHub\mojito\mojito\koreainvestment.py", line 832, in fetch_kospi_symbols
    df = self.parse_kospi_master(base_dir)
  File "C:\Users\brayden\Documents\GitHub\mojito\mojito\koreainvestment.py", line 702, in parse_kospi_master
    df1 = pd.read_csv(tmp_fil1, header=None, names=part1_columns)
  File "C:\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1235, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 544, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 734, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1952, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 23: invalid start byte
```

**Comment by brayden-jo** [comment]
csv 파일로 여는 경우 cp949로 인코딩을 사용함.
